#!/usr/bin/env bash
set -e # halt script on error

jekyll build && htmlproof ./_site \
        --url-ignore=/elements.heroku.com/ \
        --enforce-https \
        --file-ignore=/googleb2162d982ab64976.html/ \
        --check-favicon
